### ISSUE TITLE
originate fails due to type: array in package "prompt"

### ISSUE THREAD

**Issue by pelonpelon** [knomedia/originate-react-component#1]
From readme in npm package prompt:
"Arrays that do not have maxItems defined will require users to SIGINT (^C) before the array is ended."

authors and keywords fail unless (^C) is used as above.

**Comment by knomedia** [comment]
Thanks pelonpelon, somehow missed this issue getting posted. Any feedback on what would be the best solution here? Maybe adding some text to the prompt (i.e. `list of authors (^C to complete list)` ). Not sure how to best say that. Ideas?
